version: !!str 3
services:
  authz:
    image: authz:1
    depends_on:
      - mysql
    env_file: .authz_env
    environment:
      - SKOB_AUTHZ_USER_DEFAULT_STATUS=active
    expose:
      - "8080"
    labels:
      - "local.dwsclass.service=authz"
    restart: unless-stopped
    networks:
      - nginx
      - database
  mysql:
    image: mysql:8
    env_file: .mysql_env
    expose:
      - "3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    networks:
      - database
volumes:
  mysql_data:
networks:
  database:
  nginx:
    external: true

