version: !!str 3
services:
  nginx:
    image: nginx:1.21
    restart: unless-stopped
    expose:
      - "80"
      - "443"
    networks:
      - nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
networks:
  nginx:
    external: true
